import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, posix } from "node:path";
import { brotliCompressSync, constants, gzipSync } from "node:zlib";
import { decode } from "@jridgewell/sourcemap-codec";
import { GENERATED_HEADER } from "../../../src/build/generate.ts";
import { importsOf, lex } from "../../../src/build/lex.ts";
import {
	isComposedEscape,
	type PeerProvenance,
	type ProvenanceResolver,
	sha256,
} from "./provenance.ts";

/**
 * Sourcemap attribution and compression for size scenarios. Generated byte spans are assigned to the source of their
 * mapping segment: `node_modules/spinetab/**` → Spinetab (per dist file),
 * other packages → peer, scenario sources → app, unmapped → bundler runtime.
 * A composed peer source outside its store entry's package (Turbopack
 * composes upstream maps: `graphql@17.0.2/node_modules/src/…`) is keyed to
 * the installed package only with verified input-map provenance
 * (provenance.ts); otherwise it keeps its path-derived key.
 *
 * Spinetab gzip is the gzip of the Spinetab text reconstructed from the
 * chunk: contiguous Spinetab spans joined exactly as emitted, one newline
 * between runs that the chunk separates (other code or a line break). It is
 * an estimate (Spinetab code compresses differently outside its chunk),
 * reported beside the full emitted chunk gzip and the differential gzip.
 * `legacySpinetabText` joins individual mapping segments with newlines.
 * It overestimates gzip size and is retained only as a comparison control.
 */

export interface Compressed {
	bytes: number;
	gzip: number;
	brotli: number;
}

export function compressed(input: string | Buffer): Compressed {
	const buffer = typeof input === "string" ? Buffer.from(input) : input;
	return {
		bytes: buffer.byteLength,
		gzip: gzipSync(buffer, { level: 9 }).byteLength,
		brotli: brotliCompressSync(buffer, {
			params: { [constants.BROTLI_PARAM_QUALITY]: 11 },
		}).byteLength,
	};
}

export const gzipBytes = (text: string) =>
	text.length === 0 ? 0 : gzipSync(Buffer.from(text), { level: 9 }).byteLength;

/** Spinetab-only gzip of a realm: its chunks' Spinetab texts, empty chunks skipped (0 when none). */
export const spinetabGzip = (texts: string[]) =>
	gzipBytes(texts.filter((text) => text.length > 0).join("\n"));

/** One non-empty Spinetab span of a chunk: generated line, start column, text. */
export interface SpinetabSpan {
	/** Category key suffix: the dist file or composed source. */
	file: string;
	line: number;
	start: number;
	text: string;
}

/**
 * Exact reconstruction of Spinetab code from ordered spans: spans that are
 * contiguous in the chunk (same line, one ends where the next starts) join
 * with nothing, as emitted; any other gap becomes one newline.
 */
export function joinSpans(spans: readonly SpinetabSpan[]): string {
	let text = "";
	let previous: SpinetabSpan | undefined;
	for (const span of spans) {
		if (previous) {
			const contiguous =
				previous.line === span.line &&
				previous.start + previous.text.length === span.start;
			if (!contiguous) text += "\n";
		}
		text += span.text;
		previous = span;
	}
	return text;
}

export type Category =
	| { kind: "spinetab"; file: string }
	| { kind: "peer"; name: string }
	| { kind: "app"; file: string }
	| { kind: "bundler"; file: string };

/** Classify one sourcemap source path. */
export function classifySource(source: string): Category {
	const path = source.replaceAll("\\", "/");
	const at = path.lastIndexOf("node_modules/");
	if (at >= 0) {
		const parts = path.slice(at + "node_modules/".length).split("/");
		const scoped = (parts[0] ?? "").startsWith("@");
		const name = scoped ? `${parts[0]}/${parts[1]}` : (parts[0] ?? "");
		const within = parts.slice(scoped ? 2 : 1).join("/");
		return name === "spinetab"
			? { kind: "spinetab", file: within }
			: { kind: "peer", name };
	}
	if (/(^|\/)(src|app)\//.test(path) && !path.includes("\0")) {
		return { kind: "app", file: path };
	}
	return { kind: "bundler", file: path };
}

export const categoryKey = (category: Category) =>
	category.kind === "spinetab"
		? `spinetab:${category.file}`
		: category.kind === "peer"
			? `peer:${category.name}`
			: category.kind;

/**
 * The generated worker. The plugin supplies it as the content
 * of the package's `worker-config` stub path (Vite `load`, the Turbopack and
 * webpack loader) without a map, so its bytes map to that path with the
 * generated text as `sourcesContent`. Only that header marks it; the stub's
 * own content, or none, keeps the stub's key (fail closed).
 */
export const GENERATED_KEY = "generated";
const STUB_KEYS = new Set([
	"spinetab:dist/worker-config.js",
	"spinetab:src/worker-config.ts",
]);

function generatedKey(pathKey: string, content: string | null | undefined) {
	return STUB_KEYS.has(pathKey) &&
		typeof content === "string" &&
		content.startsWith(GENERATED_HEADER)
		? GENERATED_KEY
		: pathKey;
}

interface RawSourceMap {
	sources: Array<string | null>;
	sourcesContent?: Array<string | null>;
	sourceRoot?: string;
	mappings: string;
}

/** A composed peer source and what its provenance check decided. */
export type ComposedSource =
	| {
			source: string;
			status: "resolved";
			key: string;
			pathKey: string;
			provenance: PeerProvenance;
	  }
	| { source: string; status: "unresolved"; key: string; reason: string };

export interface ChunkAttribution {
	/** Bytes per category key (`spinetab:<file>`, `peer:<name>`, `app`, `bundler`, `unmapped`). */
	bytes: Record<string, number>;
	/** Spinetab text reconstructed exactly (`joinSpans`), for the Spinetab-only gzip. */
	spinetabText: string;
	/** Non-empty Spinetab spans in chunk order (per-file texts, e.g. a helper's own area). */
	spinetabSpans: SpinetabSpan[];
	/** Normalised source paths listed by the chunk's sourcemap. */
	sources: string[];
	/** Composed peer sources that carry bytes, resolved or not (resolver given). */
	composed: ComposedSource[];
	mapped: boolean;
	/** The map read (path null when inline) and the sha256 of its text. */
	mapFile: { path: string | null; sha256: string } | null;
	/** `compare` only: bytes under path-derived keys (no provenance). */
	pathBytes?: Record<string, number>;
	/** `compare` only: the newline-per-segment text (every segment joined by a newline). */
	legacySpinetabText?: string;
	/** Generated worker code in this chunk, joined as emitted (present only when there is some). */
	generatedText?: string;
	/** Each distinct generated worker module (its `sourcesContent`) that carries bytes. */
	generatedSources?: string[];
}

export interface AttributeOptions {
	/** Verifies composed peer sources (provenance.ts); without it keys are path-derived. */
	resolver?: ProvenanceResolver;
	/** Also return `pathBytes` and `legacySpinetabText` (re-attribution comparisons). */
	compare?: boolean;
}

/** A chunk's sourcemap, the file it came from (null when inline) and the sha256 of its text. */
export interface LoadedSourceMap {
	map: RawSourceMap;
	path: string | null;
	sha256: string;
}

/** Read a chunk's sourcemap from `<file>.map` or its `sourceMappingURL`. */
export function readSourceMap(
	file: string,
	code: string,
): LoadedSourceMap | undefined {
	const load = (text: string, path: string | null): LoadedSourceMap => ({
		map: JSON.parse(text) as RawSourceMap,
		path,
		sha256: sha256(text),
	});
	if (existsSync(`${file}.map`)) {
		return load(readFileSync(`${file}.map`, "utf8"), `${file}.map`);
	}
	const match = /\/\/# sourceMappingURL=(\S+)\s*$/.exec(code);
	if (!match) return undefined;
	const url = match[1] as string;
	if (url.startsWith("data:")) {
		const base64 = url.slice(url.indexOf(",") + 1);
		return load(Buffer.from(base64, "base64").toString("utf8"), null);
	}
	const path = join(dirname(file), decodeURIComponent(url));
	return existsSync(path) ? load(readFileSync(path, "utf8"), path) : undefined;
}

/** Load a chunk's sourcemap from `<file>.map` or its `sourceMappingURL`. */
export function loadSourceMap(
	file: string,
	code: string,
): RawSourceMap | undefined {
	return readSourceMap(file, code)?.map;
}

export function attributeChunk(
	file: string,
	options: AttributeOptions = {},
): ChunkAttribution {
	const code = readFileSync(file, "utf8");
	const loaded = readSourceMap(file, code);
	if (!loaded) {
		const bytes: Record<string, number> =
			code.length === 0 ? {} : { unmapped: Buffer.byteLength(code) };
		return {
			bytes,
			spinetabText: "",
			spinetabSpans: [],
			sources: [],
			composed: [],
			mapped: false,
			mapFile: null,
			...(options.compare
				? { pathBytes: { ...bytes }, legacySpinetabText: "" }
				: {}),
		};
	}
	const { map } = loaded;
	const joined = map.sources.map((source) =>
		source === null
			? null
			: map.sourceRoot
				? posix.join(map.sourceRoot, source)
				: source,
	);
	const sources = joined.map((source) =>
		source === null ? "" : source.replaceAll("\\", "/"),
	);
	const pathKeys = joined.map((source, index) =>
		source === null
			? "unmapped"
			: generatedKey(
					categoryKey(classifySource(source)),
					map.sourcesContent?.[index],
				),
	);
	// Per source index, then folded into keys: one decode serves both views.
	const perSource = new Array<number>(map.sources.length).fill(0);
	let unmapped = 0;
	const mappings = decode(map.mappings);
	const lines = code.split("\n");
	const spans: SpinetabSpan[] = [];
	const generatedSpans: SpinetabSpan[] = [];
	const legacy: string[] = [];
	for (let line = 0; line < lines.length; line += 1) {
		const text = lines[line] as string;
		const segments = mappings[line] ?? [];
		let cursor = 0;
		for (let index = 0; index < segments.length; index += 1) {
			const segment = segments[index] as number[];
			const start = segment[0] as number;
			const end =
				(segments[index + 1]?.[0] as number | undefined) ?? text.length;
			if (start > cursor) {
				unmapped += Buffer.byteLength(text.slice(cursor, start));
			}
			const span = text.slice(start, Math.max(start, end));
			const sourceIndex = segment.length >= 4 ? (segment[1] as number) : -1;
			const pathKey = pathKeys[sourceIndex];
			if (pathKey === undefined || pathKey === "unmapped") {
				unmapped += Buffer.byteLength(span);
			} else {
				perSource[sourceIndex] =
					(perSource[sourceIndex] as number) + Buffer.byteLength(span);
				if (pathKey.startsWith("spinetab:")) {
					legacy.push(span);
					if (span.length > 0) {
						spans.push({
							file: pathKey.slice("spinetab:".length),
							line,
							start,
							text: span,
						});
					}
				} else if (pathKey === GENERATED_KEY && span.length > 0) {
					generatedSpans.push({ file: GENERATED_KEY, line, start, text: span });
				}
			}
			cursor = Math.max(cursor, end);
		}
		if (cursor < text.length) unmapped += Buffer.byteLength(text.slice(cursor));
		if (line < lines.length - 1) unmapped += 1;
	}
	const composed: ComposedSource[] = [];
	const keys = pathKeys.map((pathKey, index) => {
		const source = joined[index];
		if (
			!options.resolver ||
			source === null ||
			source === undefined ||
			!pathKey.startsWith("peer:") ||
			(perSource[index] as number) === 0 ||
			!isComposedEscape(source)
		) {
			return pathKey;
		}
		const result = options.resolver.resolve(
			source,
			map.sourcesContent?.[index],
		);
		if (!result.ok) {
			composed.push({
				source: sources[index] as string,
				status: "unresolved",
				key: pathKey,
				reason: result.reason,
			});
			return pathKey;
		}
		const key = `peer:${result.provenance.package}`;
		composed.push({
			source: sources[index] as string,
			status: "resolved",
			key,
			pathKey,
			provenance: result.provenance,
		});
		return key;
	});
	const fold = (names: string[]) => {
		const bytes: Record<string, number> = {};
		if (unmapped > 0) bytes.unmapped = unmapped;
		names.forEach((key, index) => {
			const value = perSource[index] as number;
			if (value > 0) bytes[key] = (bytes[key] ?? 0) + value;
		});
		return bytes;
	};
	const generatedSources = [
		...new Set(
			pathKeys.flatMap((key, index) =>
				key === GENERATED_KEY && (perSource[index] as number) > 0
					? [map.sourcesContent?.[index] as string]
					: [],
			),
		),
	];
	return {
		bytes: fold(keys),
		spinetabText: joinSpans(spans),
		spinetabSpans: spans,
		sources,
		composed,
		mapped: true,
		mapFile: { path: loaded.path, sha256: loaded.sha256 },
		...(options.compare
			? { pathBytes: fold(pathKeys), legacySpinetabText: legacy.join("\n") }
			: {}),
		...(generatedSpans.length > 0
			? { generatedText: joinSpans(generatedSpans) }
			: {}),
		...(generatedSources.length > 0 ? { generatedSources } : {}),
	};
}

/** `spinetab` and `spinetab/<sub>`: the package importing itself by name. */
const SELF_SPECIFIER = /^spinetab(?:\/(.+))?$/;

/**
 * Dist files reachable from the selected package exports (static and dynamic
 * imports), plus the original sources their own sourcemaps list (e.g.
 * `src/core/client.ts`). Turbopack composes input sourcemaps, so Next chunks
 * attribute Spinetab bytes to those sources; Vite keeps the dist files.
 *
 * Imports are read over significant tokens (the build scanner's lexer), so
 * import text in comments and strings is never followed. A bare
 * self-import (`spinetab`, `spinetab/<sub>`, as `dist/index.js` imports
 * `spinetab/wiring`) is followed through the packed manifest's exports, as
 * the bundler resolves it; one the manifest does not export, or a file whose
 * imports cannot be read, fails the closure instead of shrinking it.
 *
 * `aliases` applies a bundler plugin's redirects to bare self-imports: `sub → export` follows that export instead, `sub → null`
 * names a module the plugin supplies from outside the package (the
 * generated worker, the application's worker file), which is never allowed.
 */
export function spinetabClosure(
	packageDir: string,
	subpaths: string[],
	aliases: Readonly<Record<string, string | null>> = {},
): Set<string> {
	const manifest = JSON.parse(
		readFileSync(join(packageDir, "package.json"), "utf8"),
	) as {
		exports: Record<
			string,
			{ import?: { default?: string } | string; default?: string }
		>;
	};
	const exportTarget = (subpath: string, from: string) => {
		const entry = manifest.exports[subpath === "." ? "." : `./${subpath}`];
		const target =
			typeof entry?.import === "string"
				? entry.import
				: (entry?.import?.default ?? entry?.default);
		if (!target)
			throw new Error(
				`spinetab export ${subpath}${from} not found in the packed manifest`,
			);
		return posix.normalize(target.replace(/^\.\//, ""));
	};
	const queue = subpaths.map((subpath) => exportTarget(subpath, ""));
	const seen = new Set<string>();
	while (queue.length > 0) {
		const file = queue.shift() as string;
		if (seen.has(file)) continue;
		seen.add(file);
		const path = join(packageDir, file);
		if (!existsSync(path)) continue;
		const lexed = lex(readFileSync(path, "utf8"));
		if (!lexed.complete) {
			throw new Error(`${file}: imports could not be read (unclosed code)`);
		}
		for (const { specifier } of importsOf(lexed.tokens)) {
			if (/^\.{1,2}\//.test(specifier)) {
				queue.push(posix.normalize(posix.join(posix.dirname(file), specifier)));
				continue;
			}
			const self = SELF_SPECIFIER.exec(specifier);
			if (self) {
				const subpath = self[1] ?? ".";
				const target = Object.hasOwn(aliases, subpath)
					? aliases[subpath]
					: subpath;
				if (target === null || target === undefined) continue;
				queue.push(exportTarget(target, ` (${specifier} in ${file})`));
			}
		}
	}
	const allowed = new Set(seen);
	for (const file of seen) {
		const mapPath = join(packageDir, `${file}.map`);
		if (!existsSync(mapPath)) continue;
		const map = JSON.parse(readFileSync(mapPath, "utf8")) as RawSourceMap;
		const base = posix.join(posix.dirname(file), map.sourceRoot ?? "");
		for (const source of map.sources) {
			if (source) allowed.add(posix.normalize(posix.join(base, source)));
		}
	}
	return allowed;
}

/** Package names reachable from `roots` through dependencies in a pnpm install. */
export function dependencyClosure(
	projectDir: string,
	roots: string[],
): Set<string> {
	const store = join(projectDir, "node_modules", ".pnpm");
	const deps = new Map<string, Set<string>>();
	const record = (manifestPath: string) => {
		const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
			name?: string;
			dependencies?: Record<string, string>;
			optionalDependencies?: Record<string, string>;
			peerDependencies?: Record<string, string>;
		};
		if (!manifest.name) return;
		const set = deps.get(manifest.name) ?? new Set<string>();
		for (const group of [
			manifest.dependencies,
			manifest.optionalDependencies,
			manifest.peerDependencies,
		]) {
			for (const name of Object.keys(group ?? {})) set.add(name);
		}
		deps.set(manifest.name, set);
	};
	if (existsSync(store)) {
		for (const entry of readdirSync(store)) {
			const modules = join(store, entry, "node_modules");
			if (!existsSync(modules)) continue;
			for (const name of readdirSync(modules)) {
				if (name.startsWith("@")) {
					for (const scoped of readdirSync(join(modules, name))) {
						const manifest = join(modules, name, scoped, "package.json");
						if (existsSync(manifest)) record(manifest);
					}
				} else {
					const manifest = join(modules, name, "package.json");
					if (existsSync(manifest)) record(manifest);
				}
			}
		}
	}
	const reached = new Set<string>();
	const queue = [...roots];
	while (queue.length > 0) {
		const name = queue.shift() as string;
		if (reached.has(name)) continue;
		reached.add(name);
		for (const next of deps.get(name) ?? []) queue.push(next);
	}
	return reached;
}
