import {
	mkdirSync,
	mkdtempSync,
	realpathSync,
	rmSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import {
	canonicalWorker,
	createGeneratedClassifier,
	devTextLocalPaths,
	LOCAL_PATH,
	localPathsIn,
	nextWebpackEntryStub,
	nextWebpackManifest,
	parseGeneratedWorker,
	spinetabDevModules,
	stubCopyEvidence,
	wiringCopyProblems,
} from "./generated.ts";
import {
	classifySource,
	type GraphChunk,
	type IsolationReport,
	isNextLoadableManifest,
	pluginGraph,
	pluginSourceProblems,
	serverWorkerMarkers,
	webpackGraph,
	workerUrlLiterals,
} from "./inspect.ts";
import { scanBuildLog, scanConfig, scanSources } from "./workarounds.ts";

/**
 * The matrix gate's own pure logic: the generated
 * worker oracle, the wiring copy check, the plugin realm graph, the server
 * scan, the provenance shapes and the recipe-aware scans. Every case runs on
 * text taken from real outputs (check 1, the verifier's scratch builds) or
 * on a temporary tree; nothing here needs a prepared consumer.
 */

const scratch = mkdtempSync(join(tmpdir(), "spinetab-gate-"));
afterAll(() => rmSync(scratch, { recursive: true, force: true }));

const K6_EXAMPLE = [
	"// Generated by spinetab. Do not edit.",
	'import { pollingAdapter } from "spinetab/polling/runtime";',
	'import { sseAdapter } from "spinetab/sse/runtime";',
	'import { defineWorker } from "spinetab/worker";',
	'export default defineWorker(() => [pollingAdapter(), sseAdapter()], { credentialOrigins: ["https://api.example.com"] });',
].join("\n");

describe("generated worker oracle", () => {
	it("round-trips the generated worker example exactly, with or without a final line end", () => {
		expect(
			canonicalWorker(["sse", "polling"], ["https://api.example.com"]),
		).toBe(K6_EXAMPLE);
		for (const text of [K6_EXAMPLE, `${K6_EXAMPLE}\n`]) {
			const parsed = parseGeneratedWorker(text);
			expect("worker" in parsed && parsed.worker.kinds).toEqual([
				"polling",
				"sse",
			]);
		}
	});

	it("emits the empty set and one tRPC import for both kinds", () => {
		expect(canonicalWorker([])).toBe(
			[
				"// Generated by spinetab. Do not edit.",
				'import { defineWorker } from "spinetab/worker";',
				"export default defineWorker(() => []);",
			].join("\n"),
		);
		expect(canonicalWorker(["trpc-ws", "trpc-sse"])).toContain(
			'import { trpcSseAdapter, trpcWsAdapter } from "spinetab/trpc/runtime";',
		);
	});

	it.each([
		[
			"unsorted calls",
			K6_EXAMPLE.replace(
				"pollingAdapter(), sseAdapter()",
				"sseAdapter(), pollingAdapter()",
			),
		],
		["an extra comment", `${K6_EXAMPLE}\n// ${"/Users/me/app"}`],
		[
			"process.env",
			K6_EXAMPLE.replace(
				'["https://api.example.com"]',
				"[process.env.API_ORIGIN]",
			),
		],
		[
			"an origin with a path",
			K6_EXAMPLE.replace(
				"https://api.example.com",
				"https://api.example.com/v1",
			),
		],
		[
			"http: off loopback",
			K6_EXAMPLE.replace("https://api.example.com", "http://api.example.com"),
		],
	])("rejects %s", (_name, text) => {
		expect("problems" in parseGeneratedWorker(text)).toBe(true);
	});

	it("accepts allowed loopback hosts for http:", () => {
		for (const origin of [
			"http://localhost:8080",
			"http://app.localhost:3000",
			"http://127.0.0.2:8080",
			"http://[::1]:8080",
		]) {
			const text = canonicalWorker(["polling"], [origin]) as string;
			expect("worker" in parseGeneratedWorker(text), origin).toBe(true);
		}
	});
});

const SHIPPED_WIRING = [
	'import { x } from "./x.js";',
	"export const wiring = {",
	'\tworker: () => new SharedWorker(new URL("./worker.js", import.meta.url), { type: "module" }),',
	'\tlocal: () => import("./worker.js"),',
	"};",
	"//# sourceMappingURL=wiring.js.map",
].join("\n");
const DEV_WIRING = SHIPPED_WIRING.replace(
	'{ type: "module" }',
	'{ type: "module", name: "spinetab-0123456789ab" }',
);

describe("bundled auto/wiring.js copies", () => {
	it("accepts the shipped file in every output", () => {
		expect(wiringCopyProblems(SHIPPED_WIRING, SHIPPED_WIRING, false)).toEqual({
			problems: [],
		});
	});

	it("accepts the development name only in development, and returns its hash", () => {
		expect(wiringCopyProblems(DEV_WIRING, SHIPPED_WIRING, true)).toEqual({
			problems: [],
			hash: "0123456789ab",
		});
		expect(
			wiringCopyProblems(DEV_WIRING, SHIPPED_WIRING, false).problems,
		).toHaveLength(1);
	});

	it("rejects a tampered literal", () => {
		const tampered = SHIPPED_WIRING.replace("./worker.js", "./other.js");
		expect(
			wiringCopyProblems(tampered, SHIPPED_WIRING, true).problems,
		).toHaveLength(1);
	});

	it("fails closed when the copy has no sourcesContent", () => {
		const report: NonNullable<IsolationReport["plugin"]> = {
			serverWorkerCode: [],
			generated: [],
			wiringHashes: [],
			localPaths: [],
			frameworkPaths: [],
		};
		const context = {
			recipe: "plugin" as const,
			development: false,
			installed: SHIPPED_WIRING,
			roots: [],
			report,
			exercised: new Set<string>(),
		};
		expect(pluginSourceProblems("auto/wiring.js", null, context)).toHaveLength(
			1,
		);
		expect(
			pluginSourceProblems("worker-config.js", null, context),
		).toHaveLength(1);
		expect(pluginSourceProblems("build/vite.js", "x", context)[0]).toMatch(
			/build realm/,
		);
		expect(
			pluginSourceProblems("worker-config.js", K6_EXAMPLE, {
				...context,
				recipe: "one-file",
			})[0],
		).toMatch(/one-file cell/);
	});
});

const chunk = (
	name: string,
	text: string,
	sources: string[] = [],
): GraphChunk => ({ chunk: name, text, sources, appFiles: [] });
const STUB =
	"../node_modules/.pnpm/spinetab@1/node_modules/spinetab/dist/auto/worker.js";

describe("pluginGraph", () => {
	it("names the worker entry from Rolldown's template literal (Astro, real text)", () => {
		const page = chunk(
			"_astro/index.C3TWfvGD.js",
			"worker:()=>new SharedWorker(new URL(`/_astro/worker-Bpk35FUv.js`,``+import.meta.url),{type:`module`}),local:()=>U(()=>import(`./worker.BaXFOOVK.js`),[])",
		);
		const graph = pluginGraph([
			page,
			chunk("_astro/worker-Bpk35FUv.js", "x", [STUB]),
			chunk("_astro/worker.BaXFOOVK.js", "y", [STUB]),
		]);
		expect([...graph.worker]).toEqual(["_astro/worker-Bpk35FUv.js"]);
		expect([...graph.lazy]).toEqual(["_astro/worker.BaXFOOVK.js"]);
	});

	it("still reads quoted literals and webpack bootstraps", () => {
		const graph = pluginGraph([
			chunk(
				"assets/index.js",
				'new SharedWorker(new URL("./w.js", import.meta.url))',
			),
			chunk("assets/w.js", "x", [STUB]),
			chunk("static/chunks/835.js", "x", [
				"webpack://_N_E/webpack/bootstrap",
				"webpack://_N_E/./worker/live.worker.ts",
			]),
			chunk("static/chunks/728.js", "x", [
				"webpack://_N_E/./worker/live.worker.ts",
			]),
		]);
		expect([...graph.worker].sort()).toEqual([
			"assets/w.js",
			"static/chunks/835.js",
		]);
		expect([...graph.lazy]).toEqual(["static/chunks/728.js"]);
	});

	it("classifies next-monorepo's worker-option file as application code", () => {
		expect(classifySource("webpack://_N_E/./worker/live.worker.ts")).toEqual({
			kind: "app",
			path: "worker/live.worker.ts",
		});
	});
});

const PNPM =
	"webpack://consumer-vanilla-polling/./node_modules/.pnpm/spinetab@file+..+pack+spinetab-0.0.0.tgz/node_modules/spinetab/dist";
const BOOT = "webpack://consumer-vanilla-polling/webpack/bootstrap";
const JSONP = (id: string) =>
	`"use strict";(self.webpackChunkconsumer_vanilla_polling=self.webpackChunkconsumer_vanilla_polling||[]).push([[${id}],{${id}(e,t,o){}}]);`;
const HTML = new Map([["index.html", "<script defer src=main.js></script>"]]);

describe("webpack and Rspack wiring graph (check 3)", () => {
	// vanilla-polling `webpack prod` (check 3): the worker URL is run-time
	// `n.u(675)`, and `local` loads the split chunk 269 with the async 953.
	const webpackProd = [
		chunk(
			"main.js",
			"m={worker:()=>new SharedWorker(new URL(n.p+n.u(675),n.b),{type:void 0}),local:()=>Promise.all([n.e(269),n.e(953)]).then(()=>n(953))}",
			[BOOT, `${PNPM}/auto/wiring.js`, `${PNPM}/index.js`],
		),
		chunk("675.js", '(()=>{"use strict";var e={953(e,t,n){}}})();', [
			`${PNPM}/auto/worker.js`,
			BOOT,
		]),
		chunk("269.js", JSONP("269"), [
			`${PNPM}/worker-config.js`,
			`${PNPM}/polling/runtime.js`,
		]),
		chunk("953.js", JSONP("953"), [`${PNPM}/auto/worker.js`]),
	];

	it("marks the chunks the wiring's local factory loads as lazy (plugin recipes)", () => {
		const graph = webpackGraph(webpackProd, HTML, true);
		expect([...graph.worker]).toEqual(["675.js"]);
		expect([...graph.lazy].sort()).toEqual(["269.js", "953.js"]);
	});

	it("keeps L1 recipes on the application-file rule", () => {
		const graph = webpackGraph(webpackProd, HTML);
		expect([...graph.worker]).toEqual(["675.js"]);
		expect([...graph.lazy]).toEqual([]);
	});

	it("reads Rspack's bound form and webpack's named development chunks", () => {
		const rspack = webpackGraph(
			[
				chunk(
					"main.js",
					'b={worker:()=>new SharedWorker(new URL(r.p+r.u(333),r.b),Object.assign({},{type:"module"},{type:void 0})),local:()=>Promise.all([r.e(378),r.e(962)]).then(r.bind(r,953))}',
					[BOOT, `${PNPM}/auto/wiring.js`],
				),
				chunk("333.js", "(()=>{})();", [BOOT, `${PNPM}/auto/worker.js`]),
				chunk("378.js", JSONP("378"), [`${PNPM}/worker-config.js`]),
				chunk("962.js", JSONP("962"), [`${PNPM}/auto/worker.js`]),
			],
			HTML,
			true,
		);
		expect([...rspack.lazy].sort()).toEqual(["378.js", "962.js"]);
		const vendor =
			"vendors-node_modules_pnpm_spinetab_file_pack_spinetab-0_0_0_tgz_node_modules_spinetab_dist_au-e6a6e1";
		const dev = webpackGraph(
			[
				chunk(
					"main.js",
					`worker: () => new SharedWorker(new URL(/* worker import */ __webpack_require__.p + __webpack_require__.u("spinetab-4294d64b06d9"), __webpack_require__.b), { type: undefined, name: "spinetab-4294d64b06d9" }),\n\tlocal: () => __webpack_require__.e(/*! import() */ "${vendor}").then(() => (__webpack_require__(/*! ./worker.js */ "./x")))`,
					[`${PNPM}/auto/wiring.js`, BOOT],
				),
				chunk("spinetab-4294d64b06d9.js", "(() => {})();", [BOOT]),
				chunk(
					`${vendor}.js`,
					`"use strict";\n(self["webpackChunkconsumer_vanilla_polling"] = self["webpackChunkconsumer_vanilla_polling"] || []).push([["${vendor}"],{\n}]);`,
					[`${PNPM}/auto/worker.js`, `${PNPM}/worker-config.js`],
				),
			],
			new Map([["index.html", '<script defer src="main.js"></script>']]),
			true,
		);
		expect([...dev.worker]).toEqual(["spinetab-4294d64b06d9.js"]);
		expect([...dev.lazy]).toEqual([`${vendor}.js`]);
	});

	it("reads chunk loads only from the bundled auto/wiring.js", () => {
		const graph = webpackGraph(
			[
				chunk(
					"main.js",
					"x={worker:()=>new SharedWorker(new URL(n.p+n.u(1),n.b)),local:()=>n.e(953).then(()=>n(953))}",
					[BOOT, "webpack://consumer/./src/main.js"],
				),
				chunk("953.js", JSONP("953"), [`${PNPM}/auto/worker.js`]),
			],
			HTML,
			true,
		);
		expect([...graph.lazy]).toEqual([]);
	});
});

describe("Turbopack rule outputs (check 3)", () => {
	const base =
		"turbopack:///[project]/node_modules/.pnpm/spinetab@file+..+pack+spinetab-0.0.0.tgz_react@19.3.0/node_modules/spinetab/dist";

	it('reads the loader\'s `as: "*.js"` output as its input file', () => {
		expect(classifySource(`${base}/worker-config.js.js`)).toEqual({
			kind: "spinetab",
			distFile: "worker-config.js",
		});
		expect(classifySource(`${base}/auto/wiring.js.js`)).toEqual({
			kind: "spinetab",
			distFile: "auto/wiring.js",
		});
		// Only the two rule targets: any other doubled name fails its lookup.
		expect(classifySource(`${base}/index.js.js`)).toEqual({
			kind: "spinetab",
			distFile: "index.js.js",
		});
		expect(
			serverWorkerMarkers(
				"node_modules/spinetab/dist/worker-config.js.js node_modules/spinetab/dist/auto/wiring.js.js",
			),
		).toEqual([
			"spinetab/dist/auto/wiring.js",
			"spinetab/dist/worker-config.js",
		]);
	});

	it("still checks the generated text strictly", () => {
		const report = {
			serverWorkerCode: [],
			generated: [],
			wiringHashes: [],
			localPaths: [],
			frameworkPaths: [],
		};
		const context = {
			recipe: "plugin" as const,
			development: false,
			installed: "",
			roots: [],
			report,
			exercised: new Set<string>(),
		};
		const kind = classifySource(`${base}/worker-config.js.js`);
		const distFile = kind.kind === "spinetab" ? kind.distFile : "";
		expect(
			pluginSourceProblems(
				distFile,
				`${K6_EXAMPLE.replace("sseAdapter()]", "sseAdapter()] ")}`,
				context,
			),
		).toHaveLength(1);
		expect(pluginSourceProblems(distFile, K6_EXAMPLE, context)).toEqual([]);
		expect(report.generated).toHaveLength(1);
	});
});

describe("worker URL literals", () => {
	it("returns each literal whole, so a query or hash is visible", () => {
		expect(
			workerUrlLiterals(
				"new SharedWorker(new URL(`/assets/worker-caSGoZBE.js`,``+import.meta.url),{type:`module`})",
			),
		).toEqual(["/assets/worker-caSGoZBE.js"]);
		expect(
			workerUrlLiterals(
				'new SharedWorker(new URL("./w.js?o=https%3A%2F%2Fa", import.meta.url))',
			),
		).toEqual(["./w.js?o=https%3A%2F%2Fa"]);
	});
});

const LOADABLE = `self.__REACT_LOADABLE_MANIFEST='{"node_modules/.pnpm/spinetab@file+..+pack+spinetab-0.0.0.tgz/node_modules/spinetab/dist/auto/wiring.js -> ./worker.js":{"id":1728,"files":["static/chunks/15.902d5b998459865d.js","static/chunks/728.79666b31baaf8587.js"]}}';`;

describe("server scan", () => {
	it("flags worker code by marker", () => {
		expect(serverWorkerMarkers("new SharedWorker(u)")).toEqual([
			"new SharedWorker(",
		]);
		expect(
			serverWorkerMarkers(
				'require("../node_modules/spinetab/dist/polling/runtime.js")',
			),
		).toEqual(["spinetab/dist/polling/runtime.js"]);
	});

	it("exempts exactly Next's loadable manifest, by shape", () => {
		const file = "server/middleware-react-loadable-manifest.js";
		expect(isNextLoadableManifest(file, LOADABLE)).toBe(true);
		expect(isNextLoadableManifest("server/chunks/192.js", LOADABLE)).toBe(
			false,
		);
		expect(
			isNextLoadableManifest(
				file,
				LOADABLE.replace("static/chunks/15", "../server/15"),
			),
		).toBe(false);
		expect(
			isNextLoadableManifest(file, `${LOADABLE}new SharedWorker(u);`),
		).toBe(false);
	});
});

const ENTRY_STUB =
	"(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[167,177,400,819,851,896,988],{8538:()=>{}},_=>{_.O(0,[933,626,358],()=>_(_.s=8538)),_N_E=_.O()}]);";
const BUILD_MANIFEST =
	'self.__BUILD_MANIFEST={__rewrites:{afterFiles:[],beforeFiles:[],fallback:[]},__routerFilterStatic:{numItems:6,errorRate:1e-4,numBits:4,numHashes:14,bitArray:[1,1,0,0]},__routerFilterDynamic:{numItems:0,errorRate:1e-4,numBits:0,numHashes:NaN,bitArray:[]},sortedPages:["/_app"]},self.__BUILD_MANIFEST_CB&&self.__BUILD_MANIFEST_CB();';

describe("Next --webpack provenance shapes", () => {
	const path = "static/chunks/app/layout-c5cba19113c56479.js";

	it("accepts the dependency-only entry stub and nothing looser", () => {
		expect(nextWebpackEntryStub(path, ENTRY_STUB, 155)).toBeDefined();
		expect(
			nextWebpackEntryStub(
				path,
				ENTRY_STUB.replace("8538:()=>{}", '8538:()=>{fetch("/x")}'),
				170,
			),
		).toBeUndefined();
		expect(nextWebpackEntryStub(path, ENTRY_STUB, 4096)).toBeUndefined();
		expect(
			nextWebpackEntryStub("server/app/layout.js", ENTRY_STUB, 155),
		).toBeUndefined();
	});

	it("accepts the webpack build manifest as data only", () => {
		const at = "static/BUILD/_buildManifest.js";
		expect(nextWebpackManifest(at, BUILD_MANIFEST, 400, "BUILD")).toBeDefined();
		expect(
			nextWebpackManifest(at, BUILD_MANIFEST, 400, "OTHER"),
		).toBeUndefined();
		expect(
			nextWebpackManifest(
				at,
				BUILD_MANIFEST.replace('["/_app"]', '[import("/x")]'),
				400,
				"BUILD",
			),
		).toBeUndefined();
	});
});

describe("stub copies", () => {
	it("accepts only the exact bytes of the installed keep stub below static/media", () => {
		const dist = join(scratch, "dist");
		mkdirSync(join(dist, "auto"), { recursive: true });
		writeFileSync(join(dist, "auto/worker.js"), "stub\n");
		const media = "static/media/worker.0a1b.js";
		expect(stubCopyEvidence(media, Buffer.from("stub\n"), dist)).toBeDefined();
		expect(
			stubCopyEvidence(media, Buffer.from("stub\n// more"), dist),
		).toBeUndefined();
		expect(
			stubCopyEvidence("static/chunks/x.js", Buffer.from("stub\n"), dist),
		).toBeUndefined();
	});
});

const base64Map = (sources: string[]) =>
	`//# sourceMappingURL=data:application/json;charset=utf-8;base64,${Buffer.from(JSON.stringify({ version: 3, sources, mappings: "" })).toString("base64")}`;

describe("local paths (findings 12, 20)", () => {
	it("finds roots and home or temporary prefixes in text", () => {
		expect(localPathsIn("x /tmp/a /Users/me/app/src y", ["/tmp/a"])).toEqual([
			"/Users/me/app/src",
			"/tmp/a",
		]);
		expect(LOCAL_PATH.test("../src/main.js")).toBe(false);
	});

	it("decodes inline maps, including inside eval strings, and exempts only Next's ignored module", () => {
		const leak = `eval("code\\n${base64Map(["/private/var/app/src/x.js"])}")`;
		expect(devTextLocalPaths(leak, [])).toEqual(["/private/var/app/src/x.js"]);
		const next = base64Map([
			"webpack://_N_E/ignored|/private/var/app/node_modules/next/dist/build/webpack/loaders|private-next-instrumentation-client-user",
		]);
		expect(devTextLocalPaths(next, [])).toEqual([]);
		expect(
			devTextLocalPaths(
				"sourceMappingURL=data:application/json;base64,bm90IGpzb24=",
				[],
			),
		).toEqual(["an undecodable inline sourcemap"]);
	});

	it("splits a webpack development chunk into its Spinetab modules", () => {
		const text = [
			'/***/ "(app-pages-browser)/./app/page.tsx":',
			"/***/ (() => { eval('/Users/me/app') }),",
			'/***/ "(app-pages-browser)/./node_modules/spinetab/dist/auto/wiring.js":',
			'/***/ (() => { eval("x") }),',
		].join("\n");
		const modules = spinetabDevModules(text);
		expect(modules.map((module) => module.id)).toEqual([
			"(app-pages-browser)/./node_modules/spinetab/dist/auto/wiring.js",
		]);
		expect(devTextLocalPaths(modules[0]?.text ?? "", [])).toEqual([]);
		expect(spinetabDevModules("no match here")).toEqual([]);
	});
});

describe("development without bundler map metadata (c14 cells 2 and 3)", () => {
	// Shape of a real `next dev --webpack` module (next-monorepo, candidate
	// 14): relative module id and sourceURL, absolute inline-map sources.
	const evalModule = (id: string, code: string) =>
		[
			`/***/ "${id}":`,
			"/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {",
			`eval(__webpack_require__.ts(${JSON.stringify(
				`${code}\n${base64Map([`/private/var/app/node_modules/.pnpm/spinetab@1/node_modules/spinetab/${id.split("/spinetab/")[1]}`])}\n//# sourceURL=webpack-internal:///${id}\n`,
			)}));`,
			"/***/ }),",
		].join("\n");
	const worker =
		"(app-pages-browser)/../../node_modules/spinetab/dist/worker-config.js";
	const wiring =
		"(app-pages-browser)/../../node_modules/spinetab/dist/auto/wiring.js";

	it("ignores inline map sources and sourceURL, and scans the module code", () => {
		const chunk = [
			evalModule(worker, K6_EXAMPLE),
			evalModule(wiring, "export const wiring = {};"),
		].join("\n");
		const modules = spinetabDevModules(chunk);
		expect(modules.map((module) => module.id)).toEqual([worker, wiring]);
		for (const module of modules) {
			// The default (Vite responses) still reads the map sources.
			expect(devTextLocalPaths(module.text, [])).toHaveLength(1);
			expect(devTextLocalPaths(module.text, [], { mapSources: false })).toEqual(
				[],
			);
		}
	});

	it("still fails a path planted in a generated module's code", () => {
		const planted = K6_EXAMPLE.replace(
			'["https://api.example.com"]',
			'["https://api.example.com"], root: "/Users/me/app"',
		);
		const [module] = spinetabDevModules(evalModule(worker, planted));
		expect(
			devTextLocalPaths(module?.text ?? "", ["/opt/ci/app"], {
				mapSources: false,
			}),
			// Inside the escaped `eval` string the match keeps the backslash.
		).toEqual([expect.stringMatching(/^\/Users\/me\/app\b/)]);
		const [rooted] = spinetabDevModules(
			evalModule(worker, `${K6_EXAMPLE}// /opt/ci/app\n`),
		);
		expect(
			devTextLocalPaths(rooted?.text ?? "", ["/opt/ci/app"], {
				mapSources: false,
			}),
		).toEqual(["/opt/ci/app"]);
		expect(
			devTextLocalPaths(
				"sourceMappingURL=data:application/json;base64,bm90IGpzb24=",
				[],
				{ mapSources: false },
			),
		).toEqual(["an undecodable inline sourcemap"]);
	});

	it("splits a Turbopack development chunk into its Spinetab modules", () => {
		const id = (path: string) =>
			`[project]/node_modules/.pnpm/spinetab@1/node_modules/spinetab/dist/${path} [app-client] (ecmascript)`;
		const text = [
			'(globalThis["TURBOPACK"] || (globalThis["TURBOPACK"] = [])).push([typeof document === "object" ? document.currentScript : undefined,',
			`"${id("auto/worker.js")}", ((__turbopack_context__) => {`,
			'"use strict";',
			"}),",
			'"[project]/node_modules/.pnpm/next@16/node_modules/next/dist/compiled/next-devtools/index.js (raw)", (function(__turbopack_context__) {',
			'var env = {"__NEXT_DIST_DIR":"/Users/me/app/.next/dev"};',
			"}),",
			`"${id("runtime.js")}", ((__turbopack_context__) => {`,
			'const planted = "/Users/me/app";',
			"}),",
			"]);",
			"//# sourceMappingURL=chunk.js.map",
		].join("\n");
		const modules = spinetabDevModules(text);
		expect(modules.map((module) => module.id)).toEqual([
			id("auto/worker.js"),
			id("runtime.js"),
		]);
		// Exempt Next's devtools define, but still scan Spinetab code.
		expect(
			modules.flatMap((module) =>
				devTextLocalPaths(module.text, [], { mapSources: false }),
			),
		).toEqual(["/Users/me/app"]);
	});

	it("classifies the next dev loader of the installed dist/auto/worker.js, and nothing else", () => {
		const root = join(scratch, "next-dev-loader");
		const store = "node_modules/.pnpm/spinetab@file+pack_react@19/node_modules";
		const dist = join(root, store, "spinetab/dist");
		mkdirSync(join(dist, "auto"), { recursive: true });
		writeFileSync(join(dist, "auto/worker.js"), "export {};\n");
		writeFileSync(join(dist, "runtime.js"), "export {};\n");
		symlinkSync(
			join(root, store, "spinetab"),
			join(root, "node_modules/spinetab"),
		);
		// A second copy that is not the installed package.
		const other = "node_modules/.pnpm/spinetab@other/node_modules";
		mkdirSync(join(root, other, "spinetab/dist/auto"), { recursive: true });
		writeFileSync(
			join(root, other, "spinetab/dist/auto/worker.js"),
			"export {};\n",
		);
		const chunks = [
			"static/chunks/1o1h_spinetab_dist_1usak_3._.js",
			"static/chunks/app_0f1_zfj._.js",
		];
		const loader = (path: string) =>
			[
				'(globalThis["TURBOPACK"] || (globalThis["TURBOPACK"] = [])).push([typeof document === "object" ? document.currentScript : undefined,',
				`"[project]/${path} [app-client] (ecmascript, async loader)", ((__turbopack_context__) => {`,
				"",
				"__turbopack_context__.v((parentImport) => {",
				"    return Promise.all([",
				chunks.map((chunk) => `  "${chunk}"`).join(",\n"),
				"].map((chunk) => __turbopack_context__.l(chunk))).then(() => {",
				`        return parentImport("[project]/${path} [app-client] (ecmascript)");`,
				"    });",
				"});",
				"}),",
				"]);",
			].join("\n");
		const file = "dev/static/chunks/1o1h_spinetab_dist_auto_worker_18an_44.js";
		const classify = createGeneratedClassifier({
			shapes: ["turbopack-dev"],
			installedDist: realpathSync(join(root, "node_modules/spinetab/dist")),
			outputFiles: [file, ...chunks.map((chunk) => `dev/${chunk}`)],
			projectRoot: root,
		});
		const kind = (path: string) =>
			classify(file, Buffer.from(loader(path)), "empty-sections")?.provenance;
		for (const path of [
			`${store}/spinetab/dist/auto/worker.js`,
			"node_modules/spinetab/dist/auto/worker.js",
		]) {
			expect(kind(path)).toMatchObject({ shape: "dev-async-loader" });
		}
		// Another installed file, a copy outside the installed package, and
		// the same text under any other map form stay unclassified.
		expect(kind(`${store}/spinetab/dist/runtime.js`)).toBeUndefined();
		expect(kind(`${other}/spinetab/dist/auto/worker.js`)).toBeUndefined();
		expect(
			classify(
				file,
				Buffer.from(loader(`${store}/spinetab/dist/auto/worker.js`)),
				"empty",
			),
		).toBeUndefined();
	});
});

describe("recipe-aware scans", () => {
	const NEXT_KEYS = [
		"turbopack",
		"turbopack.resolveAlias",
		"turbopack.resolveAlias.spinetab/wiring",
		"turbopack.resolveAlias.spinetab/wiring.browser",
		"turbopack.rules",
		"turbopack.rules.**/spinetab/dist/worker-config.js",
		"turbopack.rules.**/spinetab/dist/worker-config.js.as",
		"turbopack.rules.**/spinetab/dist/worker-config.js.condition",
		"turbopack.rules.**/spinetab/dist/worker-config.js.condition.path",
		"turbopack.rules.**/spinetab/dist/worker-config.js.loaders",
		"webpack",
	];
	const types = "turbopack?: x; resolveAlias?: x; rules?: x; webpack?: x;";

	it("admits exactly withSpinetab's keys in a plugin cell", () => {
		expect(scanConfig("next", NEXT_KEYS, [], types, "plugin")).toEqual({
			outside: [],
			undeclared: [],
			plugins: [],
		});
	});

	it("reports a hand-written alias or rule beside the wrapper", () => {
		const scan = scanConfig(
			"next-webpack",
			[
				...NEXT_KEYS,
				"turbopack.resolveAlias.spinetab/sse",
				"turbopack.rules.*.svg",
			],
			[],
			types,
			"plugin",
		);
		expect(scan.outside).toEqual([
			"turbopack.resolveAlias.spinetab/sse",
			"turbopack.rules.*.svg",
		]);
	});

	it("forbids plugin keys in L1 cells and requires the plugin in plugin cells", () => {
		expect(
			scanConfig("next", NEXT_KEYS, [], types, "one-file").outside,
		).toEqual(NEXT_KEYS);
		expect(scanConfig("next", [], [], types, "plugin").plugins).toEqual([
			"missing:withSpinetab",
		]);
		expect(scanConfig("vite", [], [], "", "plugin").plugins).toEqual([
			"missing:name:spinetab",
		]);
		expect(
			scanConfig("vite", [], ["name:spinetab", "name:spinetab"], "", "plugin")
				.plugins,
		).toEqual(["duplicate:name:spinetab"]);
	});

	it("forbids worker factories and seam specifiers in plugin sources", () => {
		const root = join(scratch, "app");
		mkdirSync(join(root, "src"), { recursive: true });
		writeFileSync(
			join(root, "src/main.js"),
			'import { wiring } from "spinetab/wiring";\nnew SharedWorker(new URL("./w.js", import.meta.url), { type: "module" });\n',
		);
		const rules = scanSources(root, ["src"], "plugin").violations.map(
			(violation) => violation.rule,
		);
		expect(rules).toContain("a worker factory in a plugin recipe");
		expect(rules).toContain("a Spinetab seam specifier in application code");
		expect(
			scanSources(root, ["src"], "plugin-worker").violations,
		).toContainEqual({
			file: "(none)",
			rule: "exactly one spinetab.worker file (L2)",
		});
	});

	it("flags every [spinetab] build line", () => {
		expect(
			scanBuildLog("ok\n[spinetab] no-adapters: no spinetab source imports"),
		).toHaveLength(1);
	});
});
